Add support for managing more resources in DaaS
citrix/terraform-provider-citrix pull request #9
Opened 2023-10-27 15:53 UTC by zhuolun-liu-citrix

* Support managing hypervisors, resource pools, machine catalogs and delivery groups.
* Show detailed error message for different client creation errors.
* Bugfixes

2023-10-27 16:04 UTC, AlanCitrix requested changes

2023-10-27 16:04 UTC, AlanCitrix commented on go.mod
> +	github.com/citrix/citrix-daas-rest-go v0.2.1
```suggestion
	github.com/citrix/citrix-daas-rest-go v0.2.2
```

2023-10-27 19:19 UTC, AlanCitrix approved these changes

2023-11-02 14:41 UTC, aneeshk-citrix approved these changes

2023-11-02 15:05 UTC, AlanCitrix approved these changes

2023-11-02 15:12 UTC, merged